import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
=======
import { Schibsted_Grotesk, Martian_Mono } from "next/font/google";
import "./globals.css";
import LightRays from "@/components/LightRays";
import Navbar from "@/components/Navbar";

const SchibstedGrotesk = Schibsted_Grotesk({
>>>>>>> 2a283abd01a1c1f3a73843009da40ec0ddb9392a
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

<<<<<<< HEAD
const geistMono = Geist_Mono({
=======
const martianMono = Martian_Mono({
>>>>>>> 2a283abd01a1c1f3a73843009da40ec0ddb9392a
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "DevEvent",
  description: "The Hub for every Dev Event You Mustn't Miss",
>>>>>>> 2a283abd01a1c1f3a73843009da40ec0ddb9392a
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {children}

=======
        className={`${SchibstedGrotesk.variable} ${martianMono.variable} min-h-screenantialiased`}
      >
      <Navbar/>

        <div className="absolute inset-0 top-0 z-[-1] min-h-screen">
          <LightRays
            raysOrigin="top-center-offset"
            raysColor="#5dfeca"
            raysSpeed={0.5}
            lightSpread={0.9}
            rayLength={1.4}
            followMouse={true}
            mouseInfluence={0.02}
            noiseAmount={0.0}
            distortion={0.1}
           
    
          />
        </div>
        <main>
          {children}
        </main>
        
>>>>>>> 2a283abd01a1c1f3a73843009da40ec0ddb9392a
      </body>
    </html>
  );
}
<<<<<<< HEAD


=======
>>>>>>> 2a283abd01a1c1f3a73843009da40ec0ddb9392a
